module kpsr_dds_vision_ocv {

    struct ImageData {
        string frameId;
        short seq; //@key
        long timestamp;

        unsigned long rows;
        unsigned long cols;
        unsigned long type;
        sequence<octet, 500000> data;
    };

#pragma keylist ImageData seq
};
