name: Check build

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  builddebug:
    name: Vanilla Debug
    runs-on: ubuntu-latest
    container:
      image: 337955887028.dkr.ecr.eu-central-1.amazonaws.com/amd64:base-1.4.2
      options: --user root
      credentials:
        username: AWS
        password: ${{ secrets.ECR_PASSWORD }}
    steps:
      - name: Clone kpsr-core
        uses: actions/checkout@v3
        with:
          repository: klepsydra-technologies/kpsr-core
          submodules: recursive
          ref: main
          path: kpsr-core

      - name: Install kpsr-core
        run: |
          mkdir build && cd build 
          cmake -DKPSR_WITH_DOXYGEN=true -DKPSR_WITH_DDS=false -DKPSR_WITH_ZMQ=false -DKPSR_TEST_PERFORMANCE=false -DKPSR_WITH_SOCKET=true -DKPSR_WITH_YAML=false -DKPSR_WITH_CODE_METRICS=true -DCMAKE_BUILD_TYPE=Debug -DKPSR_ENABLE_TESTS=false -DKPSR_ENABLE_EXAMPLES=false ../
          make -j$(nproc)
          make test
          sudo make -j$(nproc) install
        working-directory: kpsr-core

      - name: Upload kpsr_codegen
        uses: actions/upload-artifact@v3
        with:
          name: kpsr_codegen
          path: |
            kpsr-core/build/kpsr_codegen-1.0-py3-none-any.whl

      - name: Remove kpsr-core sources
        run: |
          sudo rm -rf ${GITHUB_WORKSPACE}/kpsr-core

      - name: Clone kpsr-robotics
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          mkdir build && cd build 
          cmake -DKPSR_WITH_DOXYGEN=true -DCMAKE_BUILD_TYPE=Debug -DKPSR_WITH_OCV=true -DKPSR_ENABLE_TESTS=true -DKPSR_ENABLE_EXAMPLES=true ../
          make -j$(nproc)

      - name: Unit tests
        timeout-minutes: 10
        run: cd build && make test ARGS="--gtest_shuffle"

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: builddebug-logs
          path: |
            build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeError.log
            build/Testing/Temporary
            build/code_generator/kpsr_codegen/build_cpptesting/Testing/Temporary

      - name: Workspace cleanup
        if: always()
        run: |
          sudo rm -rf ${GITHUB_WORKSPACE}/build

  buildrelease:
    needs: builddebug
    strategy:
      matrix:
        include:
          - name: Vanilla
            zmq: "false"
            dds: "false"

          - name: ZMQ
            zmq: "true"
            dds: "false"

    name: ${{ matrix.name }} Release
    runs-on: ubuntu-latest
    container:
      image: 337955887028.dkr.ecr.eu-central-1.amazonaws.com/amd64:base-1.4.2
      options: --user root
      credentials:
        username: AWS
        password: ${{ secrets.ECR_PASSWORD }}
    steps:
      - name: Clone kpsr-core
        uses: actions/checkout@v3
        with:
          repository: klepsydra-technologies/kpsr-core
          submodules: recursive
          ref: main
          path: kpsr-core

      - name: Install kpsr-core
        run: |
          mkdir build && cd build 
          cmake -DKPSR_WITH_DOXYGEN=false -DKPSR_WITH_DDS=${{ matrix.dds }} -DKPSR_WITH_ZMQ=${{ matrix.zmq }} -DKPSR_TEST_PERFORMANCE=false -DKPSR_WITH_SOCKET=true -DKPSR_WITH_YAML=false -DKPSR_WITH_CODE_METRICS=true -DCMAKE_BUILD_TYPE=Release -DKPSR_ENABLE_TESTS=false -DKPSR_ENABLE_EXAMPLES=false ../
          make -j$(nproc)
          sudo make -j$(nproc) install
        working-directory: kpsr-core

      - name: Remove kpsr-core sources
        run: |
          sudo rm -rf ${GITHUB_WORKSPACE}/kpsr-core

      - name: Clone kpsr-robotics
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: >
          mkdir build && cd build &&
          cmake -DKPSR_WITH_DOXYGEN=false -DKPSR_WITH_CODE_METRICS=true -DCMAKE_BUILD_TYPE=Release
          -DKPSR_WITH_OCV=true -DKPSR_ENABLE_TESTS=false -DKPSR_ENABLE_EXAMPLES=false 
          -DKPSR_VERSION_PATCH=$(git rev-parse --short HEAD) ../ &&
          make -j$(nproc)

      - name: Create deb packages
        run: |
          cpack -G DEB
          ls -la | grep deb
        working-directory: build

      - name: Store deb packages
        uses: actions/upload-artifact@v3
        with:
          name: deb-packages-${{ matrix.name }}
          path: build/*.deb

      - name: Create tarballs
        run: |
          sudo cpack -G TGZ
        working-directory: build

      - name: Store tarballs
        uses: actions/upload-artifact@v3
        with:
          name: tgz-packages-${{ matrix.name }}
          path: build/*.tar.gz

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs-${{ matrix.name }}
          path: |
            build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeError.log
            build/Testing/Temporary
            build/code_generator/kpsr_codegen/build_cpptesting/Testing/Temporary

      - name: Workspace cleanup
        if: always()
        run: |
          sudo rm -rf ${GITHUB_WORKSPACE}/build

  ros:
    needs: builddebug
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rosrelease: ["noetic"]
    name: ROS ${{ matrix.rosrelease }}
    env:
      ROS_DISTRO: ${{ matrix.rosrelease }}
    container:
      image: "337955887028.dkr.ecr.eu-central-1.amazonaws.com/amd64:${{ matrix.rosrelease }}-1.2.2"
      options: --user root
      credentials:
        username: AWS
        password: ${{ secrets.ECR_PASSWORD }}
    steps:
      - name: Clone kpsr-core
        uses: actions/checkout@v3
        with:
          repository: klepsydra-technologies/kpsr-core
          submodules: recursive
          ref: main
          path: kpsr-core

      - name: Install kpsr-core
        run: |
          mkdir build && cd build 
          cmake -DKPSR_WITH_DOXYGEN=false -DKPSR_WITH_DDS=false -DKPSR_WITH_ZMQ=false -DKPSR_TEST_PERFORMANCE=false -DKPSR_WITH_SOCKET=true -DKPSR_WITH_YAML=true -DKPSR_WITH_CODE_METRICS=false -DKPSR_ENABLE_TESTS=false -DKPSR_ENABLE_EXAMPLES=false -DCMAKE_BUILD_TYPE=Release ../
          make -j$(nproc)
          make test
          sudo make install
        working-directory: kpsr-core

      - name: Clone kpsr-robotics
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: kpsr-robotics

      - name: Build
        run: |
          mkdir -p build && cd build
          cmake -DKPSR_WITH_DOXYGEN=true -DKPSR_WITH_DDS=false -DKPSR_WITH_ZMQ=false -DKPSR_WITH_CODE_METRICS=true -DKPSR_WITH_OCV=true -DCMAKE_BUILD_TYPE=Release -DKPSR_ENABLE_TESTS=true -DKPSR_ENABLE_EXAMPLES=false ../
          make -j$(nproc)
        working-directory: kpsr-robotics

      - name: Unit tests
        timeout-minutes: 10
        run: |
          cd build
          make test ARGS="--gtest_shuffle"
        working-directory: kpsr-robotics

      - name: Install
        run: |
          cd build
          sudo make install
        working-directory: kpsr-robotics

      - name: Create ROS environment
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          mkdir -p ${GITHUB_WORKSPACE}/kpsr-ros/src/build
          cd ${GITHUB_WORKSPACE}/kpsr-ros/src
          catkin_init_workspace
          ln -s ${GITHUB_WORKSPACE}/kpsr-core/core/modules/ros_mdlw/kpsr_ros_core . 
          ln -s ${GITHUB_WORKSPACE}/kpsr-core/serialization/modules/ros_mdlw/kpsr_ros_serialization .
          ln -s ${GITHUB_WORKSPACE}/kpsr-core/code_generator/cpp_testing/tests/kpsr_ros_codegen .
          ln -s ${GITHUB_WORKSPACE}/kpsr-robotics/geometry/modules/ros_mdlw/kpsr_ros_geometry .
          ln -s ${GITHUB_WORKSPACE}/kpsr-robotics/uav_sensors/modules/ros_mdlw/kpsr_ros_sensors .
          ln -s ${GITHUB_WORKSPACE}/kpsr-robotics/vision_ocv/modules/ros_mdlw/kpsr_ros_vision_ocv .

      - name: Build ROS
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd ${GITHUB_WORKSPACE}/kpsr-ros/src/build
          cmake ../
          make -j$(nproc)

      - name: Test ROS
        timeout-minutes: 15
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd ${GITHUB_WORKSPACE}/kpsr-ros/src/build
          make tests

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ros-${{ matrix.rosrelease }}
          path: |
            build/Testing/Temporary
            build/code_generator/kpsr_codegen/build_cpptesting/Testing/Temporary
            ${GITHUB_WORKSPACE}/kpsr-ros/src/build/Testing/Temporary
            ${GITHUB_WORKSPACE}/kpsr-ros/src/build/test_results

      - name: Workspace cleanup
        if: always()
        run: |
          sudo rm -rf ${GITHUB_WORKSPACE}/build
